### PR TITLE
RDSS-2122 updating diagram, removing internal services, adding 854 an…

### PR DESCRIPTION
**Pull request by fractos**
…d 1203, and adding various adaptors to the HEI representations.

### CODE REVIEW

**Comment by fractos** [comment]
It's true, I bailed on trying to make the diagram better. I think we'd have to burn it first.

**Comment by fractos** [comment]
@fmcc can you have another look now please?

**Comment by fmcc** [comment]
Point 2) from the PR still needs changed, and is it worth including Middlesex, SGUL and the Surrey in the Per-HEI block if there are no services producing/consuming messages in the clusters for them?

**Comment by fractos** [comment]
@fmcc ok, try that now please

**Pull request merged**
