### PR TITLE
Merge of 'feature/rdss-1869_generator_header' branch into 'develop' branch

### PR DESCRIPTION
**Pull request by danielgrant**

### CODE REVIEW

**Comment by danielgrant** [comment]
@michalc,

> There is a fair bit here that I don't think is covered by the ticket... I wonder if the commits should be split to something like...

I don't see much advantage to this - the changes I made above and beyond the scope of the ticket were just tightening up the JSON schema, at no point was any "new" functionality introduced. In fact, if this was a release that contained _only_ these chnages, I would have released them with a patch version number.

> Some of the above I think might need some more documentation changes? e.g. machineId is still listed as a string?

I have updated this.

> For example, there is going to be a version bump PR about this?

Yes there will be.

> It would make it easier for the person reviewing that to reason about what sort of semver change the actual changes are split up a bit, so can work out the "maximum" change?

This release is planned as a major release (i.e. `2.0.0`). As mentioned previously, the changes above and beyond the scope of the original ticket are patch changes.

There are no peer review required for release merges - everything moving into `develop` is peer reviewed so it can be safely assumed that anything in `develop` has met the necessary standards.

> Also, this is one of the open repositories: would make it easier for people to understand how the spec is changing/being refined. Especially if they need to create messages that will be validated?

I will add notes to the release to this effect.

> Also, if there is some issue with a change, would make the history easier to look through and see when and how it happened?

The commit histories are present in the repository, and I don't think breaking every tiny little change down into its own commit is going to help. I think that doing so can hinder under some circumstances, as the commit history becomes bloated and difficult to traverse.

> (Also: I'm actually not sure about the use of some of the $ref fields that are just used in the one place. It seems to make it more difficult to at-a-glance understand what a valid structure is? Say, if I was making something that output messages, I have to now jump around more places? But I'm not sure how these files are actually to be used, so hard for me to know what a good structure is

The `$ref`'s are used to break objects out for the purposes of:
- maintainability, such that you don't have to traverse an overly complicated / embedded JSON structure; and
- re-usability, though granted right now that there are some objects that are only used in one place, but this approach future proofs and maintains consistency.

The sample JSON payload and associated documentation in `README.md` provide a reader with what a payload should look like, combined with an understanding of the data model. The JSON schema documents are designed to constrain payloads, and not necessarily describe how to produce them, and I think that anyone consuming the API specification would be sufficiently technical to be able to follow the `$ref`'s.

**Comment by michalc** [comment]
All fair enough

(Although the one thing that I think I do disagree with is one of the reasons for the `$ref`s... you now have to traverse _more_ rather than less? But maybe if it's just how I reason about things, so there is no perfect solution...)

Just to check though, you're deliberately _not_ making more changes to the Readme for the other fields? e.g. `machineAddress` that is listed as a string in the readme, but now must be `ipOrHostName` in the schema? And the various fields that are now nonEmptyString

**Comment by danielgrant** [comment]
> Just to check though, you're deliberately not making more changes to the Readme for the other fields? e.g. machineAddress that is listed as a string in the readme, but now must be ipOrHostName in the schema?

Ah, I see your point now. I'll update the `README.md` to reflect this constraint.

> And the various fields that are now nonEmptyString

I don't think this is necessary - whether or not a string *MUST* be provided is defined by its multiplicity, i.e. `[1]`, `[0..1]`, etc. The purpose of `nonEmptyString` is to ensure that where a string field has been provided, that it's not blank, i.e. `""`. I consider this more of a "belts and braces" thing to ensure that generators are not generating a blank field, rather than an explicit type / requirement that needs documented in the `README.md`.

**Comment by danielgrant** [comment]
> Just to check though, you're deliberately not making more changes to the Readme for the other fields? e.g. machineAddress that is listed as a string in the readme, but now must be ipOrHostName in the schema?

Actually, after looking at the `README.md`, I think the current description of this field is correct.
It is a string field in the JSON payload, so a type of `string` is correct, and then the actual description itself details the constraints.

**Comment by michalc** [comment]
>  I consider this more of a "belts and braces" thing to ensure that generators are not generating a blank field, rather than an explicit type / requirement that needs documented in the README.md.

This might speak to my lack of knowledge of how this is all to be used, I probably have a fair number of incorrect assumptions, but I think the Readme is to be used by people writing generators? If I were writing a generator, I would probably start with the minimum that achieves the thing that works, and getting the message processed is a higher priority than leaving a correct audit trail. So I might leave various fields blank just to get them through validation and the payload through, i.e. strings that I believe can be `""` I would leave as `""`. According to the readme, this should work. However, they then won't be validated, and potentially rejected by stricter parts of the system. This feels misleading?

But again, I'm not sure of the use cases for the readme, or even the schema(!), so it's hard for me to judge whether what's there is helpful or a hindrance.

**Comment by danielgrant** [comment]
> So I might leave various fields blank just to get them through validation and the payload through, i.e. strings that I believe can be "" I would leave as "". According to the readme, this should work.

I'm not sure what part of the `README.md` implies that blank strings should work? Where a field is optional, it is omitted entirely. Otherwise, it has to be populated with a value.

**Comment by michalc** [comment]
> I'm not sure what part of the README.md implies that blank strings should work? Where a field is optional, it is omitted entirely. Otherwise, it has to be populated with a value.

e.g. here? https://github.com/JiscRDSS/rdss-message-api-specification/tree/48cc303800a28b52614ef2ad6b33fbe76b8b49ec#machineid

**Comment by danielgrant** [comment]
I'm confused - perhaps I'm missing something:

```
machineId
Multiplicity:    1
Type:              String
The ID of the machine that generated the history entry.
```

It's a mandatory field (multiplicity of 1), that represents the ID of the generating machine. I don't see anything that would suggest you can leave the field blank.

**Comment by michalc** [comment]
> Actually, after looking at the README.md, I think the current description of this field is correct.
It is a string field in the JSON payload, so a type of string is correct, and then the actual description itself details the constraints.

Ah, there are non-raw JSON types already? e.g. `Type: Timestamp`, which is a constraint on a String? So it might be inconsistent for some things to be "raw" JSON strings, and others to be strings with constraints?

**Comment by michalc** [comment]
> It's a mandatory field (multiplicity of 1), that represents the ID of the generating machine.

Ah: an empty string is still a string? By the type checkers I'm familiar with, then it's a string

_But_ I suddenly realise I'm not sure how `multiplicity` is applied when validating... trying to find out...

**Comment by michalc** [comment]
I think I'm quite confused by the `multiplicity`! What is meant by this?

**Comment by danielgrant** [comment]
> Ah, there are non-raw JSON types already? e.g. Type: Timestamp, which is a constraint on a String? So it might be inconsistent for some things to be "raw" JSON strings, and others to be strings with constraints?

Where the JSON Schema specification provides a mechanism for constraining a field to a particular type, we'll try and use that. For example, the `format` keyword lets us constrain `string` fields to certain types, e.g. `hostname`, `ipv6`, `date-time`, etc. Where we can't constrain a field (in the case of `machineId`, we can't really predict how a machine will choose to identify itself), so we require only that the field is non-blank (i.e. `nonEmptyString`).

> I think I'm quite confused by the multiplicity! What is meant by this?

With regards to multiplicity, it's just the standard multiplicity concept inherited from the data model:

- `[0..1]` - optional, can appear 0 or 1 times
- `[0..n]` - optional, can appear 0 to many times (i.e. an array)
- `[1..n]` - mandatory, can appear 1 to many times (i.e. an array)
- `[1]` - mandatory, must appear exactly once

**Comment by michalc** [comment]
Understood about multiplicity, but perhaps I'm confused about how it translates to JSON, i.e. a string of multiplicity of 1 is just a string, but, a multiplicity of '2' means it's an array of strings? Feels a bit odd somehow to be "injecting" a level of types here. (Happy to not push this though, _definitely_ beyond the scope to change the entire readme!)

> Where we can't constrain a field (in the case of machineId)

According to the new schema, it _is_ constrained, i.e. nonEmptyString, so I wonder if it should be communicated into the readme? Just like the other constraints?

**Pull request merged**
